### ISSUE TITLE
Q2 Porter Issues

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#180]
https://github.com/agrc/porter/issues

**Comment by nathankota** [comment]
### Tasks
- [ ] Follow-up with DHHS Licensing and Background Checks about Health Facilities data
  - https://github.com/agrc/porter/issues/256
  - https://github.com/agrc/porter/issues/257

**Comment by gregbunce** [comment]
- [ ] https://github.com/agrc/porter/issues/226
- [ ] https://github.com/agrc/porter/issues/225

**Comment by gregbunce** [comment]
@DenisePeterson and I meeting on Nov 29 to work on these.

**Comment by steveoh** [comment]
Can we get an update on https://github.com/agrc/porter/issues/256 and https://github.com/agrc/porter/issues/257?

**Comment by nathankota** [comment]
Q3 task will be created to track new/ongoing Porter issues
