### ISSUE TITLE
DEQ - UIC Inventory Approval

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#306]
### Benefit

- Finalize the steps and app behaviors for UIC admin approval of well inventories.
- Deal with any bugs/issues that arise during testing of the features/tasks that are part of Acceptance Criteria.
- Advance the app towards a production ready-state.

### Acceptance Criteria

- [x] Any remaining pieces of https://github.com/uic-utah/uic-inventory/issues/273
- [x] https://github.com/uic-utah/uic-inventory/issues/282
- [x] https://github.com/uic-utah/uic-inventory/issues/275
- [x] https://github.com/uic-utah/uic-inventory/issues/276 (part of 279, below)
- [x] https://github.com/uic-utah/uic-inventory/issues/280
- [x] https://github.com/uic-utah/uic-inventory/issues/274
- [x] https://github.com/uic-utah/uic-inventory/issues/279
- [x] https://github.com/uic-utah/uic-inventory/issues/278 (merged with 277, below)
- [x] https://github.com/uic-utah/uic-inventory/issues/277
- [x] https://github.com/uic-utah/uic-inventory/issues/271
- [x] https://github.com/uic-utah/uic-inventory/issues/287
- [x] https://github.com/uic-utah/uic-inventory/issues/288

### Notes

[Inventory Approval GitHub Milestone](https://github.com/uic-utah/uic-inventory/milestone/4)
[Project Board](https://github.com/orgs/uic-utah/projects/1/views/2)

### Risks

Accept: Client testing and feedback
Mitigate: Client expectations as new tasks present themselves

### Issue Reference

refs #307

**Comment by nathankota** [comment]
### Sprint 2
- https://github.com/uic-utah/uic-inventory/issues/282

**Comment by steveoh** [comment]
### Sprint 1 Notes

- completed these tasks and waiting to prioritize feedback + scheduling any feedback

**Comment by nathankota** [comment]
### Sprint 2

- https://github.com/uic-utah/uic-inventory/issues/282

**Comment by nathankota** [comment]
### Sprint 5
- Review Ryan's new approval workflow and define related tasks

**Comment by nathankota** [comment]
Within the quarter/PI it was decided that data transfer from the app database to the UIC database was not feasible. This altered the workflow of the approval process, which will be addressed in Q4.
