### ISSUE TITLE
Dev Team Innovation and Planning (FY24 Q4)

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#376]
### Benefit

The final sprint of the quarter is meant to be an [Innovation and Planning (IP) Iteration](https://scaledagileframework.com/innovation-and-planning-iteration/). Benefits include:
- Allow time for Innovation
- Dedicate time to PI Events (I&A and PI planning)
- Integrate the Complete Solution (presentation of work of all teams on the train)
- Advance Development Infrastructure
- Enable Continuous Learning

Possible tasks include:
- Pay down technical debt
  - app and data dependencies and updates
  - updating CIs
- Other modernization tasks
- Cloud migration
- "Work on whatever with whomever"
- Alignment of best practices

#### Possible Tasks  
- [x] https://github.com/agrc/raster/issues/169
- [ ] Consider https://github.com/step-security/harden-runner this quarter or another
- [ ] Revisit the [reactfire npm conflicts](https://github.com/FirebaseExtended/reactfire/pull/594)
- [ ] Some action workflows are not completing since their required checks aren’t running
- [x] Push swapper to pypi and automate builds https://github.com/agrc/swapper/issues/19
- [x] https://github.com/agrc/skid/pull/8
- [x] Migrate to [actions/create-github-app-token](https://github.com/actions/create-github-app-token)
- [ ] Migrate to Artifact Registry
  - [ ] geocode-job
  - [ ] unclaimed property
  - [x] roadkill
  - [x] masquerade
  - [x] parole
  - ~[ ] cambiador~
- [ ] Palletjack: https://github.com/agrc/planning-queue/issues/274
- ~Masquerade:~
  - ~https://github.com/agrc/planning-queue/issues/91~
  - ~https://github.com/agrc/planning-queue/issues/281~
- [x] Upgrade Pro version on Forklift machine 
- Skid readme's
  - [ ] https://github.com/agrc/uorg-skid/issues/3
  - [ ] https://github.com/agrc/dabs-skid/issues/4
  - [ ] https://github.com/agrc/wmrc-skid/issues/33
  - [ ] https://github.com/agrc/broadband-speedtest-skid/issues/5
- [x] Bump [agrc/get-next-version-action](https://github.com/agrc/get-next-version-action/issues/142) to Node JS v20
- [x] Bump [agrc/release-composite-action](https://github.com/agrc/release-composite-action/issues/48) to Node JS v20
- [ ] Release pipeline: Separate deployments releases by moving them to a separate workflow that is triggered by published releases. This would make it easier to rerun them if there was an issue with the deploy.

### Issue Reference

refs #311

**Comment by nathankota** [comment]
Copied from #311, before moving more of the Acceptance Criteria tasks to here, and closing 311. 

![Image](https://github.com/agrc/planning-queue/assets/15659642/b7e14e1a-19fb-4225-84db-ad88a302f030)

**Comment by nathankota** [comment]
### Sprint 6
- [ ] https://github.com/agrc/raster/issues/169 (@jacobdadams ?)

**Comment by steveoh** [comment]
### Sprint 6 Notes (Steve)

- Atlas improvements
  - Started to replace reactfire from atlas
  - Started to incorporate design system elements
  - Started to restructure the UI
- Design system improvements
  - Evaluated building blocks for design system and chose to migrate to react-aria 
  - Created sherlock component
  - Created Header component
  - Created Footer component
  - Created Social component
  - Started Button component
  - Started Input component
  - Started Dartboard component building on Button and Inputs. Stuck on react hook form integration.
- API Client improvements
  - Migrated to an improved build system with vite
  - Created universal builds for intel and arm based systems
  - Added a beta channel for testing new features
- gis.utah.gov improvements
  - Evaluated broken link checker and created list of links to triage
- UIC improvements After finding out UIC was in production
  - Fixed a bug with admin notifications
  - Added a link to a help doc that was created
  - Fixed a bug with database columns not matching input size limits
