### ISSUE TITLE
WMRC: Used Oil Collection Center (UOCC) Inspection Report Automation

### ISSUE THREAD

**Issue by jacobdadams** [agrc/planning-queue#428]
### Benefit

An automated system using Survey123, webhooks, and Make will speed up the UOCC inspection process and make sure reports are both being saved to the right locations and go out to relevant parties immediately. Will allow WMRC to get rid of paper form process.

### Acceptance Criteria

- [ ] Suvey123 version of existing forms, with "switch" question to include the proper health department inspectors. 
- [ ] Make automation to generate the report, email it to the inspectors and people being inspected, and save it to Google Drive
- [ ] Feature services containing the inspector lists and UOCCs so that the survey doesn't have to be republished every time they're updated

### Notes

One of the Local Health Departments (LHDs) has already done a proof of concept, we just need to implement it statewide.

### Risks

- Difficulties translating the Survey123 form
- Funding for Make automation
- Credits for report generation

### Issue Reference

refs #

**Comment by steveoh** [comment]
Has the state have an enterprise account for Make or at least an approval to use it?

**Comment by nathankota** [comment]
### Sprint 4
- get in touch with Ted Sonnenberg (sp?) from WMRC

**Comment by jacobdadams** [comment]
### 25.1.5

Met with Ted Sonnenberg, Rachel Boyer, and Stevie on 5 Sept to discuss next steps. 

#### Goal 

S123 form that will provide a different list of inspectors (from feature service) and UOCCs (from feature service) based on LHD. Gateway condition will be a code that each LHD has. S123 and all supporting data will be public.

After a response is submitted, a Make workflow will generate a PDF report and save it to a Google Drive folder based on the LHD. If possible, it will also look for a "email me a copy" question and if yes, send a copy of the PDF to the email address provided by the UOCC. The Make workflow will also save the data in a google sheet, with a separate tab for each LHD if possible.

#### Tasks

- [x] Contact Jonathan Dutrow to get copy of XLSForm and Make automation workflow
- [x] See if Make can condition on a response in the data to send copy to UOCC
- [ ] See if Make can send the data to different tabs in a Google Sheet
- [ ] Set up Inspector and UOCC feature services (may be able to use existing facility layer from map to get UOCC info)
- [ ] Create Survey
- [ ] Create Make Automation

**Comment by jacobdadams** [comment]
### 25.1.6

WMRC shuffled funds around and removed the end-of-September deadline. Now this can be finished in early Q2.

**Comment by jacobdadams** [comment]
### 25.2.3

Fighting with S123 Connect and LibreOffice not being able to update the XLSForm document.

**Comment by jacobdadams** [comment]
### 25.2.4

Meeting with WMRC folks on UOCC stuff on 4 Dec

**Comment by jacobdadams** [comment]
### 25.3.3

Met with WMRC folks on 7 Feb to refresh current goals and plan, based on https://docs.google.com/document/d/1F18xeWUdoBng2TCsMsYt2rFpB93CXCJFQUxA3CgAGQE. 

- UOCC data for S123 can be updated weekly (may make sense to do daily combined with data updates)
- UOCC contact info will be put into its own sheet that we can both pull from and push updated info to
- "Collection period" will be a dropdown of "1- Jan-June" and "2- July-Dec" or something like that.
- Completed records should be transferred to two places:
  - One master sheet containing all the records
  - Individual sheets for each local health district in their respective folders

**Comment by jacobdadams** [comment]
### 26.1.1

Submitted dev version of make.com automation and uocc-skid to WMRC for approval. Waiting to hear back from Rachel.

**Comment by jacobdadams** [comment]
### 26.1.3

Updated make.com automation to gracefully handle missing email addresses. 

Re-ran dev version of uocc-skid and sent email seeking final approval (6 Aug).

**Comment by jacobdadams** [comment]
### 26.1.4

2025-08-13: Rachel requested the script also update the contacts sheet as well

**Comment by jacobdadams** [comment]
### 26.2.1

2025-10-07: Published final initial version of uocc-skid (1.0.1). This marks the completion of all the initial work. I sent an email to everyone, but there were a lot of OOF responses so we may not hear back from them for a bit.
