### ISSUE TITLE
WRI - remove focus areas and replace HUC12

### ISSUE THREAD

**Issue by nathankota** [agrc/planning-queue#45]
## Benefit
WRI is dropping the project ranking criteria around focus areas, and using a new HUC level instead.

## Acceptance Criteria
- [Remove Focus Areas](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/12)
- [Replace HUC12 with HUC10](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/13)

## Risks
DTS and WRI engagement

**Comment by nathankota** [comment]
- [ ] [Remove Focus Areas](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/12)
- [ ] [Replace HUC12 with HUC10](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/13)

**Comment by nathankota** [comment]
### Sprint 5
- [ ] [Remove Focus Areas](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/12)
- [ ] [Replace HUC12 with HUC10](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/13)

**Comment by nathankota** [comment]
### Sprint 5
- [ ] [Remove Focus Areas](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/12)
- [ ] [Replace HUC12 with HUC10](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/13)

**Comment by steveoh** [comment]
### Sprint 5 Notes

#### AT Changes

- Focus areas were removed from the api and application
  - someone needs to request the table is dropped from the database
- HUC10 was published to the map but with the wrong label expression
- The API was updated from dotnet core 3.1 to dotnet 6

**Comment by steveoh** [comment]
## Production Release Notes

- checked out prod branch, opened reference mxd and published. (Focus areas were already removed, thanks scott!)
- installed dotnet 6 hosting bundle and sdk
- built the api and published

**Comment by nathankota** [comment]
- Tested and validated prod app. 
- [New GitLab issue created for Focus Area table removal by DTS](https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/14)
- Closing this and the GitLab issues.
  - https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/12
  - https://git.dts.utah.gov/sixthfloor-east/wri/-/issues/13
